name: Job Scraper Bot

on:
  schedule:
    - cron: "0 */8 * * *"  # Runs every 8 hours
  workflow_dispatch:  # Allows manual triggers

jobs:
  scrape-and-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Write Firebase Credentials to File
        run: echo '${{ secrets.FIREBASE_CREDENTIALS_JSON }}' > /tmp/firebase_credentials.json

      - name: Set Up Environment Variables
        run: |
          echo "FIREBASE_CREDENTIALS_PATH=/tmp/firebase_credentials.json" >> $GITHUB_ENV
          echo "EMAIL_ADDRESS=${{ secrets.EMAIL_ADDRESS }}" >> $GITHUB_ENV
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV
          echo "RECIPIENT_EMAIL=${{ secrets.RECIPIENT_EMAIL }}" >> $GITHUB_ENV
          echo "LOCATION=${{ secrets.LOCATION }}" >> $GITHUB_ENV
          echo "SMTP_SERVER=${{ secrets.SMTP_SERVER }}" >> $GITHUB_ENV
          echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> $GITHUB_ENV

      - name: Run Job Scraper
        run: python main.py  # Run the scraper

      - name: Send Job Alert Emails
        run: python email_service/send_email.py